name: Continuous Integration
run-name: Multi platform build and test for ${{ github.ref }} by ${{ github.actor }}
on:
  pull_request_target:
    branches: [ $default-branch ]
  push:
    branches-ignore: []

jobs:
  Build-and-Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, ]
        compiler: [ clang, gcc ]
            
        include:
          - os: macos-latest
            compiler: clang
            c_compiler: $(brew --prefix llvm@15)/bin/clang
            cpp_compiler: $(brew --prefix llvm@15)/bin/clang++
            
          - os: macos-latest
            compiler: gcc
            c_compiler: gcc-13
            cpp_compiler: g++-13
            
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang-15
            cpp_compiler: clang++-15
            
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++

          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure CMake
        run: > 
          cmake -B build -S ${{ github.workspace }}
          -DCMAKE_BUILD_TYPE=Release
          -DUTILSCPP_INCLUDE_TESTS=ON
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          
      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: GTEST_COLOR=1 ctest --output-on-failure
